### ISSUE TITLE
RecentFileManager.java

### ISSUE THREAD

**Issue by Jang-Woo-Jin** [Jang-Woo-Jin/OOP_final#2]
기능은 실행된시간과 뮤직파일 하나씩 넣게ㅇㅇ
add delete

**Comment by lyuha** [comment]
@Jang-Woo-Jin RecentFileManager라는 건 무슨 의미냐. GUI까지 구현하라는 소리인가? 
add / delete 기능이 필요하고, 그에 따라서 Container에 실행된 시간과 mp3 파일 경로를 쌍으로 저장하란 소리입니까?

**Comment by lyuha** [comment]
@Jang-Woo-Jin 하나씩 넣는데 실행된 시간은 Date/Time까지 필요한가? 아니면 날짜만 필요한가?
뮤직 파일이란 건 String Type을 주는건가?

**Comment by Jang-Woo-Jin** [comment]
Gui 는 아니고 실행시간과 musicFIle 객체를 가지고있으면 좋지않을까 함

**Comment by Jang-Woo-Jin** [comment]
흠 아까 나왔던대로 시간은 저장하지말고 그냥 music 객체를 실행한 순서대로 가지고있게 하면 됨
